version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies"
      - npm install
  pre_build:
    commands:
      - echo "Running lint checks"
      - npm run lint
  build:
    commands:
      - echo "Starting build process"
      - npm run build
  post_build:
    commands:
      - echo "Running tests"
      - npm test

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: build

cache:
  paths:
    - node_modules/**/*
