version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies"
      - npm install
  pre_build:
    commands:
      - echo "Running lint checks"

  build:
    commands:
      - echo "Starting build process"

  post_build:
    commands:
      - echo "Running tests"
