version: 0.2

phases:
  pre_build:
    commands:
      - echo "Running lint checks"

  build:
    commands:
      - echo "Starting build process"

  post_build:
    commands:
      - echo "Running tests"
